SCR_MissionHeader {
 World "{C74554CCCEC8F165}Worlds/ExplosiveFuelAssets.ent"
 m_sName "Test world"
 m_sAuthor "Vultur"
 m_sDescription "<Insert world description>"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}